language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest --debug
after_success:
  - bash <(curl -s https://codecov.io/bash)